### ISSUE TITLE
Can the official website provide multilingual support?

### ISSUE THREAD

**Issue by chaozwn** [AstroNvim/docs#100]
If we can provide the corresponding translation files, is it possible to add multilingual support to the official website?

**Comment by mehalter** [comment]
This is a great idea. Here is a resource just in case anyone picks this up to the i18n documentation for Docusaurus: https://docusaurus.io/docs/i18n/introduction#overview

**Comment by Uzaaft** [comment]
#112  When merged will make this easier.

**Comment by mehalter** [comment]
Yeah, I added that PR as closing this issue. It will be doing all of the setup for multilingual support. It will just require people to sit down and make the translations for pages! If you want to try doing a translation @chaozwn , I can definitely help you get it set up. It would also be good for us to document the process and put that in the docs so other people can easily add translations!
