### ISSUE TITLE
Following the instructions in AstroNvim websites does not work.

### ISSUE THREAD

**Issue by yossijacob** [AstroNvim/docs#108]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.1

### Operating system/version

popos

### Terminal/GUI

bash

### Describe the bug

Following the instructions in AstroNvim websites does not work.
After cloning the user configuration from [https://github.com/username/astronvim_config.git](https://github.com/username/astronvim_config.git) . If you then try and follow the recipe for the NvChad Telescope Theme [https://astronvim.com/Recipes/telescope_theme](https://astronvim.com/Recipes/telescope_theme) .
it will not work. the recipe says to edit your user/init.lua file by adding a highlights = {..
This will not work because there is a highlight directory cloned from the user example configuration which apparently override that setting.

### Steps to Reproduce

Just follow the instruction for creating a user config from the AstroNvim website

[https://astronvim.com/Configuration/manage_user_config](https://astronvim.com/Configuration/manage_user_config)
[https://astronvim.com/Recipes/telescope_theme](https://astronvim.com/Recipes/telescope_theme)

### Expected behavior

The example should change to either show an example adding to the `highlight/init.lua`  or there should be a warning that it will not work while there is a highlight directory.

**Comment by mehalter** [comment]
All of the docs recipes are communicated through the minimal user configuration necessary which is a single `user/init.lua` file. You are correct that if you split up the user configuration then the split files take precedence. You just need to put the relevant information into the correct place. Here is the docs for which tables correspond to which files in a split up user configuration: https://astronvim.com/Configuration/config_options
