### ISSUE TITLE
Add instructions how to "uninstall" astronvim

### ISSUE THREAD

**Issue by sieste** [AstroNvim/docs#71]
### Is your feature related to a problem?

I followed the instructions to install astronvim, backing up the .config/nvim and .local/share/nvim subdirectories. After playing around with it I wanted to go back to my old nvim configuration. I moved the backed up subdirectories back to their original names. Now whenever I open nvim I get a long list of errors like 

```
line   35:
E117: Unknown function: plug#begin
line   37:
E492: Not an editor command: Plug 'jpalardy/vim-slime'
line   39:
E492: Not an editor command: Plug 'ap/vim-buftabline'
line   41:
E492: Not an editor command: Plug 'itchyny/calendar.vim'
line   43:
.....
```

and all my plugins are broken.

### Describe the new feature

Document how to completely undo the astronvim installation and recover the previous nvim configuration.

**Comment by sieste** [comment]
It seems like vim-plug was removed during my installation/deinstallation of astronvim. Reinstalling vim-plug with ```curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim``` fixed the  issue.

**Comment by mehalter** [comment]
Yeah it looks like you have something going on on your machine that is not good. AstroNvim does not use `vim-plug`

**Comment by mehalter** [comment]
Finished in the latest commit to v4 branch
